version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  converter:
    build:
      context: ./Converter
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: converter
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    command: server /data

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
   postgres-data:
   minio-data:
   rabbitmq-data: